### PR TITLE
Fix generated write typings when `WebResource` are included

### PR DESCRIPTION
**Pull request by Page-**
Change-type: patch

### CODE REVIEW

**Comment by otaviojacobi** [comment]
@Page- Why is this necessary and not the other typings? This WebResource typing should ever only be read as this (and the writing is done by uploading a file)

**Comment by Page-** [comment]
@otaviojacobi the write typings refer to the `WebResource` interface, I was just adding the import so that the generated typings can be valid. If the correct typing is for them to not use that interface and instead use something else then feel free to PR that instead

**Comment by Page-** [comment]
You can check the test at https://github.com/balena-io-modules/abstract-sql-to-typescript/blob/v2.1.4/test/index.ts which has the write typings referring to a `WebResource` type which doesn't exist in that context

**Comment by otaviojacobi** [comment]
I see. This is a bit messy right now then, as what currently happens is that the [SDK replaces the WebResource typing on writes](https://github.com/balena-io/balena-sdk/blob/34986e7746a8e948685c3603353ed2257b84b181/typings/pinejs-client-core.d.ts#L386). I guess the correct thing to do here is to have the proper write type as something like

```
interface WebResourceWrite extends Blob {
    name: string;
}
```

For the write typings, which requires a major

**Comment by otaviojacobi** [comment]
Actually the SDK does not use the abstract-sql-to-typescript thing, it is manually mantained, so it doesn't really matter, I will PR a major with the correct write typings. The problematic part is that `pinejs` also supports node 16, so it will probably require a major in there aswell....

**Comment by otaviojacobi** [comment]
@Page-  See https://github.com/balena-io-modules/abstract-sql-to-typescript/pull/54

**Pull request closed without merging**
